[project]
name = "first-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "google-adk>=1.5.0",
    "google-genai>=1.24.0",
    "httpx>=0.28.1",
    "mcp[cli]>=1.10.1",
    "requests>=2.32.4",
]
